// Code generated by "stringer -type=EventType"; DO NOT EDIT.

package github

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeCommit-1]
	_ = x[TypeCodeScanningAlert-2]
	_ = x[TypeDependabotAlert-3]
	_ = x[TypeIssue-4]
	_ = x[TypePullRequest-5]
	_ = x[TypePullRequestReview-6]
	_ = x[TypeRelease-7]
	_ = x[TypeRepositoryRenamed-8]
	_ = x[TypeRepositoryPublic-9]
	_ = x[TypeSecurityAdvisory-10]
	_ = x[TypeSecretScanningAlert-11]
	_ = x[TypeTeam-12]
	_ = x[TypeWorkflow-13]
	_ = x[TypeWorkflowJob-14]
	_ = x[TypeUnknown-15]
}

const _EventType_name = "TypeCommitTypeCodeScanningAlertTypeDependabotAlertTypeIssueTypePullRequestTypePullRequestReviewTypeReleaseTypeRepositoryRenamedTypeRepositoryPublicTypeSecurityAdvisoryTypeSecretScanningAlertTypeTeamTypeWorkflowTypeWorkflowJobTypeUnknown"

var _EventType_index = [...]uint8{0, 10, 31, 50, 59, 74, 95, 106, 127, 147, 167, 190, 198, 210, 225, 236}

func (i EventType) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_EventType_index)-1 {
		return "EventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventType_name[_EventType_index[idx]:_EventType_index[idx+1]]
}
